# Generated by Django 6.0 on 2026-01-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='address',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='stage',
        ),
        migrations.AddField(
            model_name='lead',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Call', 'Call Done'), ('Followup', 'Follow-up'), ('Registered', 'Registered'), ('Installed', 'Installed'), ('Completed', 'Setup Done')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
