# Generated by Django 6.0 on 2026-01-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_remove_lead_address_remove_lead_stage_lead_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='message',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='status',
        ),
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('Call', 'Call Done'), ('Follow-up', 'Follow-up'), ('Registration', 'Registration Confirmed'), ('Installation', 'Installation Started'), ('Setup', 'Setup Done')], default='Call', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
