# Generated by Django 6.0 on 2026-01-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_remove_lead_message_remove_lead_status_lead_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='stage',
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('Call', 'Call'), ('Follow-up', 'Follow-up'), ('Registration', 'Registration'), ('Installation', 'Installation'), ('Setup Done', 'Setup Done')], default='Call', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
