# Generated by Django 6.0 on 2026-01-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_remove_lead_status_lead_message_lead_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='message',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='stage',
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Call', 'Call'), ('Follow-up', 'Follow-up'), ('Registration', 'Registration'), ('Installation', 'Installation'), ('Setup Done', 'Setup Done')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
