# Generated by Django 6.0 on 2026-01-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_remove_lead_message_remove_lead_stage_lead_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Qualified', 'Qualified'), ('Converted', 'Converted'), ('Lost', 'Lost')], default='New', max_length=20),
        ),
    ]
