# Generated by Django 6.0 on 2026-01-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_message_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Call', 'Call'), ('Follow-up', 'Follow-up'), ('Registration', 'Registration'), ('Installation', 'Installation'), ('Setup Done', 'Setup Done')], default='New', max_length=20),
        ),
    ]
