# Generated by Django 5.2 on 2026-01-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_alter_lead_message_alter_lead_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='message',
        ),
        migrations.AlterField(
            model_name='lead',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New Enquiry'), ('contacted', 'Contacted'), ('survey', 'Site Survey'), ('quote', 'Quotation Sent'), ('won', 'Won'), ('lost', 'Lost'), ('install', 'Installation')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadnote',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
