# Generated by Django 5.2 on 2026-01-31 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_remove_lead_message_alter_lead_id_alter_lead_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='customer_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(default='Call', max_length=50),
        ),
    ]
