# Generated by Django 5.2 on 2026-01-31 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_lead_customer_type_alter_lead_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='customer_type',
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New Enquiry'), ('contacted', 'Contacted'), ('survey', 'Site Survey'), ('quote', 'Quotation Sent'), ('won', 'Won'), ('lost', 'Lost'), ('install', 'Installation')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='leadnote',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead'),
        ),
        migrations.CreateModel(
            name='LeadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lead_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
        ),
    ]
