# Generated by Django 6.0 on 2026-02-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_delete_solarpower_lead_message_alter_installation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='message',
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quote', 'Quote'), ('converted', 'Converted')], default='new', max_length=20),
        ),
    ]
