# Generated by Django 5.2 on 2026-02-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_alter_installation_id_alter_lead_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
