# Generated by Django 6.0 on 2026-02-20 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_lead_follow_up_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadimage',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='leadnote',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='lead',
        ),
        migrations.AddField(
            model_name='lead',
            name='assign_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='avg_monthly_bill',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='campaign',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='financing_preference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='installation_type',
            field=models.CharField(blank=True, choices=[('On Grid', 'On Grid'), ('Off Grid', 'Off Grid'), ('Hybrid', 'Hybrid')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='medium',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='roof_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='sanctioned_load',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Installation',
        ),
        migrations.DeleteModel(
            name='LeadImage',
        ),
        migrations.DeleteModel(
            name='LeadNote',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
