# Generated by Django 5.2 on 2026-02-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='assign_to',
            new_name='assigned_to',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='avg_monthly_bill',
            new_name='average_monthly_bill',
        ),
        migrations.AddField(
            model_name='lead',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='lead_profiles/'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='campaign',
            field=models.CharField(blank=True, default='General', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial')], max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='financing_preference',
            field=models.CharField(blank=True, default='Cash', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='installation_type',
            field=models.CharField(blank=True, choices=[('domestic', 'Domestic'), ('commercial', 'Commercial'), ('residential', 'Residential')], default='Residential', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='medium',
            field=models.CharField(blank=True, default='Online', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='remarks',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='roof_type',
            field=models.CharField(blank=True, default='Flat', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='sanctioned_load',
            field=models.CharField(blank=True, default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, default='Direct', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('call', 'Call'), ('contacted', 'Contacted'), ('quote', 'Quote'), ('converted', 'Converted')], default='new', max_length=50),
        ),
    ]
