# Generated by Django 5.2 on 2026-02-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_rename_assign_to_lead_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(default='New', max_length=50),
        ),
    ]
