# Generated by Django 5.2 on 2026-02-24 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_alter_lead_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='average_monthly_bill',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='customer_type',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='financing_preference',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='installation_type',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='medium',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='roof_type',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='sanctioned_load',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='source',
        ),
        migrations.AddField(
            model_name='lead',
            name='follow_up_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('pending', 'Pending')], default='new', max_length=20),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
