# Generated by Django 5.2 on 2026-02-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0024_lead_average_monthly_bill_lead_campaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='installation_type',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('offgrid', 'Off Grid')], max_length=100, null=True),
        ),
    ]
